name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - name: Checkout Repository
     - uses: actions/checkout@v2

     - name: Change Directory to startup_code
       run: cd startup_code

     - name: Execute assign1
       run: ./assign1
